# Generated by Django 4.2.3 on 2023-07-03 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercreation',
            name='created_at',
        ),
    ]
