# Generated by Django 4.2.3 on 2023-07-03 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_usercreation_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercreation',
            name='approved',
        ),
    ]
