# Generated by Django 4.2.3 on 2023-07-06 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_rename_winners_event_location_remove_event_photos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventphoto',
            name='event',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='EventPhoto',
        ),
    ]
