# Generated by Django 4.2.3 on 2023-07-04 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_usercreation_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercreation',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usercreation',
            name='token',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
    ]
